CREATE DATABASE COMPANY
GO
USE COMPANY
--1)TABLE EMPLOYEE
CREATE TABLE EMPLOYEE(
SSN INT PRIMARY KEY,
Fname varchar(50) NOT NULL,
lname varchar(50) NOT NULL,
BIRTH_DATE DATE,
gender char check (gender='M' or gender='m' or gender='F' or gender ='f'),
SUPERSSN INT ,
DNUM INT
FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE(SSN)
    ON DELETE NO ACTION
    ON UPDATE no action

)
--2)Create the DEPARTMENT table
CREATE TABLE DEPARTMENT (
DNUM INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50) unique NOT NULL,
MGR_SSN INT unique not null default 1 ,
HIRING_DATE date Default getdate()
FOREIGN KEY (MGR_SSN) REFERENCES EMPLOYEE(ssn)
        ON DELETE  no action
        ON UPDATE cascade
)
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_DNUM FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
        on delete  no action
        ON UPDATE no action
--INSERT INTO employee 5 mangers of 5 department
INSERT INTO EMPLOYEE
VALUES(1, 'YAHYA', 'RAMDAN','2001-12-04' , 'M', NULL, NULL);
INSERT INTO EMPLOYEE
VALUES(5, 'EHAP', 'RAMDAN','2001-12-04',  'M', 1, NULL),(2, 'YOUSSEF', 'RAMDAN','2001-12-04',  'M', 1, NULL),(3, 'MOHAMED', 'RAMDAN','2001-12-04',  'M', 1, NULL),(4, 'SAPER', 'RAMDAN','2001-12-04' , 'M', 1, NULL)
SELECT *
FROM EMPLOYEE
----insert 5 department
INSERT INTO DEPARTMENT (DNUM, DEPARTMENT_NAME, MGR_SSN, HIRING_DATE)
VALUES
(10, 'HR', 1, '2020-01-01'),
(20, 'IT', 2, '2020-02-01'),
(30, 'Finance', 3, '2020-03-01'),
(40, 'Marketing', 4, '2020-04-01'),
(50, 'Logistics', 5, '2020-05-01');
select * from DEPARTMENT
-----insert into emplyee the department for mangers
UPDATE EMPLOYEE
SET DNUM = 10 WHERE SSN = 1;
UPDATE EMPLOYEE
SET DNUM = 20 WHERE SSN = 2;
UPDATE EMPLOYEE
SET DNUM = 30 WHERE SSN = 3;
UPDATE EMPLOYEE SET
DNUM = 40 WHERE SSN = 4;
UPDATE EMPLOYEE
SET DNUM = 50 WHERE SSN = 5;
SELECT *FROM EMPLOYEE
-----constraints between tables 
ALTER TABLE EMPLOYEE
ALTER COLUMN DNUM INT NOT NULL;
ALTER TABLE DEPARTMENT
ALTER COLUMN MGR_SSN INT NOT NULL;
----CREATE DEPARTMENT LOCATIONS
CREATE TABLE DEPARTMENT_LOCTION
(
DNUM INT REFERENCES DEPARTMENT(DNUM) 

,
_LOCATION VARCHAR(255 ) NOT NULL
PRIMARY KEY(DNUM,_LOCATION))
---CREATE TABLE DEPENDET
CREATE TABLE DEPENDENT 
(SSN INT,
DEPENDENT_NAME VARCHAR(50),
BIRTH_DATE DATE,
gender char check (gender='M' or gender='m' or gender='F' or gender ='f'),
PRIMARY KEY(SSN,DEPENDENT_NAME)
)
--Create the PROJECT table
CREATE TABLE PROJECT(
PNumber int primary key,
Pname varchar(50) not null,
city varchar(50),
DNUM INT NOT NULL REFERENCES DEPARTMENT(DNUM)
 ON DELETE NO ACTION
 ON UPDATE no action
)
------CREATE TABLE EMPLOYEE_PROJECT
CREATE TABLE EMPLOYEE_PROJECT
(EMP_SSN INT REFERENCES EMPLOYEE(SSN),
EMP_PNUM INT REFERENCES PROJECT(PNUMBER),
HOURS FLOAT 
PRIMARY KEY(EMP_SSN,EMP_PNUM))
--ADDTIONAL 1)Adding a new column
ALTER TABLE EMPLOYEE
ADD  SALARY FLOAT 

ALTER TABLE EMPLOYEE
ADD CONSTRAINT DF_EMPLOYEE_SALARY DEFAULT 1000.0 FOR SALARY;
UPDATE  EMPLOYEE
SET SALARY =5000
--ADDTIONAL 4)Dropping an existing constraint
ALTER TABLE EMPLOYEE
DROP CONSTRAINT DF_EMPLOYEE_SALARY;

--ADDTIONAL 3)Modifying a column's data type
ALTER TABLE EMPLOYEE
ALTER COLUMN SALARY DECIMAL(10,2)

------------------------------------------------------------------------------------------
