// <auto-generated />
using System;
using DemoDay4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoDay4.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20250815084051_addUser")]
    partial class addUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoDay4.Models.Course", b =>
                {
                    b.Property<int>("CrsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Crs_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsId"));

                    b.Property<int?>("CrsDuration")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Duration");

                    b.Property<string>("CrsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Crs_Name");

                    b.Property<int?>("TopId")
                        .HasColumnType("int")
                        .HasColumnName("Top_Id");

                    b.HasKey("CrsId");

                    b.HasIndex("TopId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Id");

                    b.Property<string>("DeptDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Dept_Desc");

                    b.Property<string>("DeptLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dept_Location");

                    b.Property<int?>("DeptManager")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Manager");

                    b.Property<string>("DeptName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dept_Name");

                    b.Property<DateOnly?>("ManagerHiredate")
                        .HasColumnType("date")
                        .HasColumnName("Manager_hiredate");

                    b.HasKey("DeptId");

                    b.HasIndex("DeptManager");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.InsCourse", b =>
                {
                    b.Property<int>("InsId")
                        .HasColumnType("int")
                        .HasColumnName("Ins_Id");

                    b.Property<int>("CrsId")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Id");

                    b.Property<string>("Evaluation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InsId", "CrsId");

                    b.HasIndex("CrsId");

                    b.ToTable("Ins_Course", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.Instructor", b =>
                {
                    b.Property<int>("InsId")
                        .HasColumnType("int")
                        .HasColumnName("Ins_Id");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Id");

                    b.Property<string>("InsDegree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ins_Degree");

                    b.Property<string>("InsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ins_Name");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.HasKey("InsId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.StudCourse", b =>
                {
                    b.Property<int>("CrsId")
                        .HasColumnType("int")
                        .HasColumnName("Crs_Id");

                    b.Property<int>("StId")
                        .HasColumnType("int")
                        .HasColumnName("St_Id");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.HasKey("CrsId", "StId");

                    b.HasIndex("StId");

                    b.ToTable("Stud_Course", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.Student", b =>
                {
                    b.Property<int>("StId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("St_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StId"));

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("Dept_Id");

                    b.Property<string>("StAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("St_Address");

                    b.Property<int?>("StAge")
                        .HasColumnType("int")
                        .HasColumnName("St_Age");

                    b.Property<string>("StFname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("St_Fname");

                    b.Property<string>("StLname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("St_Lname")
                        .IsFixedLength();

                    b.Property<int?>("StSuper")
                        .HasColumnType("int")
                        .HasColumnName("St_super");

                    b.HasKey("StId");

                    b.HasIndex("DeptId");

                    b.HasIndex("StSuper");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.Topic", b =>
                {
                    b.Property<int>("TopId")
                        .HasColumnType("int")
                        .HasColumnName("Top_Id");

                    b.Property<string>("TopName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Top_Name");

                    b.HasKey("TopId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("DemoDay4.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DemoDay4.Models.Course", b =>
                {
                    b.HasOne("DemoDay4.Models.Topic", "Top")
                        .WithMany("Courses")
                        .HasForeignKey("TopId")
                        .HasConstraintName("FK_Course_Topic");

                    b.Navigation("Top");
                });

            modelBuilder.Entity("DemoDay4.Models.Department", b =>
                {
                    b.HasOne("DemoDay4.Models.Instructor", "DeptManagerNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("DeptManager")
                        .HasConstraintName("FK_Department_Instructor");

                    b.Navigation("DeptManagerNavigation");
                });

            modelBuilder.Entity("DemoDay4.Models.InsCourse", b =>
                {
                    b.HasOne("DemoDay4.Models.Course", "Crs")
                        .WithMany("InsCourses")
                        .HasForeignKey("CrsId")
                        .IsRequired()
                        .HasConstraintName("FK_Ins_Course_Course");

                    b.HasOne("DemoDay4.Models.Instructor", "Ins")
                        .WithMany("InsCourses")
                        .HasForeignKey("InsId")
                        .IsRequired()
                        .HasConstraintName("FK_Ins_Course_Instructor");

                    b.Navigation("Crs");

                    b.Navigation("Ins");
                });

            modelBuilder.Entity("DemoDay4.Models.Instructor", b =>
                {
                    b.HasOne("DemoDay4.Models.Department", "Dept")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_Instructor_Department");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("DemoDay4.Models.StudCourse", b =>
                {
                    b.HasOne("DemoDay4.Models.Course", "Crs")
                        .WithMany("StudCourses")
                        .HasForeignKey("CrsId")
                        .IsRequired()
                        .HasConstraintName("FK_Stud_Course_Course");

                    b.HasOne("DemoDay4.Models.Student", "St")
                        .WithMany("StudCourses")
                        .HasForeignKey("StId")
                        .IsRequired()
                        .HasConstraintName("FK_Stud_Course_Student");

                    b.Navigation("Crs");

                    b.Navigation("St");
                });

            modelBuilder.Entity("DemoDay4.Models.Student", b =>
                {
                    b.HasOne("DemoDay4.Models.Department", "Dept")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_Student_Department");

                    b.HasOne("DemoDay4.Models.Student", "StSuperNavigation")
                        .WithMany("InverseStSuperNavigation")
                        .HasForeignKey("StSuper")
                        .HasConstraintName("FK_Student_Student");

                    b.Navigation("Dept");

                    b.Navigation("StSuperNavigation");
                });

            modelBuilder.Entity("DemoDay4.Models.Course", b =>
                {
                    b.Navigation("InsCourses");

                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("DemoDay4.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DemoDay4.Models.Instructor", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("InsCourses");
                });

            modelBuilder.Entity("DemoDay4.Models.Student", b =>
                {
                    b.Navigation("InverseStSuperNavigation");

                    b.Navigation("StudCourses");
                });

            modelBuilder.Entity("DemoDay4.Models.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
